### PR TITLE
Turganov HW2

### PR DESCRIPTION
**Pull request by 1MRUN**

### CODE REVIEW

**Comment by 1MRUN** [comment]
I also done hw1 after deadline.

**Comment by kochaika** [comment]
Pull request should contain only one HomeWork
>Before submitting the pull request, make sure that you can say "YES" to each point in this short checklist:
>Pull-request changes affect only your folder and only one Home Work.

**Comment by kochaika** [comment]
@1MRUN  This PullRequest can't be merged.

**Comment by 1MRUN** [comment]
> @1MRUN This PullRequest can't be merged.

I deleted hw1

**Comment by kochaika** [comment]
> Pull-request changes affect only your folder and only one Home Work.

Delete both `.DS_Store` files please also.

**Comment by 1MRUN** [comment]
> > Pull-request changes affect only your folder and only one Home Work.
> 
> Delete both `.DS_Store` files please also.

done

**Comment by kochaika** [comment]
> **both**

**Comment by 1MRUN** [comment]
> > **both**

done.

**Comment by kochaika** [comment]
https://github.com/kochaika/nand2tetris-hw-2024/actions/runs/11365686788/job/31616067775

>Test ALU: Failed (|        x         |        y         |zx |nx |zy |ny | f |no |       out        |zr |ng |
| 0000000000000000 | 1111111111111111 | 1 | 0 | 1 | 0 | 1 | 0 | 0000000000000000 | 0 | 0 |
| 0000000000000000 | 1111111111111111 | 1 | 1 | 1 | 1 | 1 | 1 | 0000000000000000 | 0 | 0 |
| 0000000000000000 | 1111111111111111 | 1 | 1 | 1 | 0 | 1 | 0 | 0000000000000000 | 0 | 1 |
| 0000000000000000 | 1111111111111111 | 0 | 0 | 1 | 1 | 0 | 0 | 0000000000000000 | 0 | 0 |
| 0000000000000000 | 1111111111111111 | 1 | 1 | 0 | 0 | 0 | 0 | 0000000000000000 | 0 | 1 |
| 0000000000000000 | 1111111111111111 | 0 | 0 | 1 | 1 | 0 | 1 | 0000000000000000 | 0 | 1 |
| 0000000000000000 | 1111111111111111 | 1 | 1 | 0 | 0 | 0 | 1 | 0000000000000000 | 0 | 0 |
| 0000000000000000 | 1111111111111111 | 0 | 0 | 1 | 1 | 1 | 1 | 0000000000000000 | 0 | 0 |
| 0000000000000000 | 1111111111111111 | 1 | 1 | 0 | 0 | 1 | 1 | 0000000000000000 | 0 | 0 |
| 0000000000000000 | 1111111111111111 | 0 | 1 | 1 | 1 | 1 | 1 | 0000000000000000 | 0 | 0 |
| 0000000000000000 | 1111111111111111 | 1 | 1 | 0 | 1 | 1 | 1 | 0000000000000000 | 0 | 0 |
| 0000000000000000 | 1111111111111111 | 0 | 0 | 1 | 1 | 1 | 0 | 0000000000000000 | 0 | 1 |
| 0000000000000000 | 1111111111111111 | 1 | 1 | 0 | 0 | 1 | 0 | 0000000000000000 | 0 | 1 |
| 0000000000000000 | 1111111111111111 | 0 | 0 | 0 | 0 | 1 | 0 | 0000000000000000 | 0 | 1 |
| 0000000000000000 | 1111111111111111 | 0 | 1 | 0 | 0 | 1 | 1 | 0000000000000000 | 0 | 0 |
| 0000000000000000 | 1111111111111111 | 0 | 0 | 0 | 1 | 1 | 1 | 0000000000000000 | 0 | 1 |
| 0000000000000000 | 1111111111111111 | 0 | 0 | 0 | 0 | 0 | 0 | 0000000000000000 | 0 | 0 |
| 0000000000000000 | 1111111111111111 | 0 | 1 | 0 | 1 | 0 | 1 | 0000000000000000 | 0 | 1 |
| 00000000000[10](https://github.com/kochaika/nand2tetris-hw-2024/actions/runs/11365686788/job/31616067775?pr=39#step:6:11)001 | 0000000000000011 | 1 | 0 | 1 | 0 | 1 | 0 | 0000000000000000 | 0 | 0 |
| 0000000000010001 | 00000000000000[11](https://github.com/kochaika/nand2tetris-hw-2024/actions/runs/11365686788/job/31616067775?pr=39#step:6:12) | 1 | 1 | 1 | 1 | 1 | 1 | 0000000000000000 | 0 | 0 |
| 0000000000010001 | 0000000000000011 | 1 | 1 | 1 | 0 | 1 | 0 | 0000000000000000 | 0 | 1 |
| 0000000000010001 | 0000000000000011 | 0 | 0 | 1 | 1 | 0 | 0 | 0000000000000000 | 0 | 0 |
| 0000000000010001 | 0000000000000011 | 1 | 1 | 0 | 0 | 0 | 0 | 0000000000000000 | 0 | 0 |
| 0000000000010001 | 0000000000000011 | 0 | 0 | 1 | 1 | 0 | 1 | 0000000000000000 | 0 | 1 |
| 0000000000010001 | 0000000000000011 | 1 | 1 | 0 | 0 | 0 | 1 | 0000000000000000 | 0 | 1 |
| 0000000000010001 | 0000000000000011 | 0 | 0 | 1 | 1 | 1 | 1 | 0000000000000000 | 0 | 1 |
| 0000000000010001 | 0000000000000011 | 1 | 1 | 0 | 0 | 1 | 1 | 0000000000000000 | 0 | 1 |
| 0000000000010001 | 0000000000000011 | 0 | 1 | 1 | 1 | 1 | 1 | 0000000000000000 | 0 | 0 |
| 0000000000010001 | 0000000000000011 | 1 | 1 | 0 | 1 | 1 | 1 | 0000000000000000 | 0 | 0 |
| 0000000000010001 | 0000000000000011 | 0 | 0 | 1 | 1 | 1 | 0 | 0000000000000000 | 0 | 0 |
| 0000000000010001 | 0000000000000011 | 1 | 1 | 0 | 0 | 1 | 0 | 0000000000000000 | 0 | 0 |
| 0000000000010001 | 0000000000000011 | 0 | 0 | 0 | 0 | 1 | 0 | 0000000000000000 | 0 | 0 |
| 0000000000010001 | 0000000000000011 | 0 | 1 | 0 | 0 | 1 | 1 | 0000000000000000 | 0 | 0 |
| 0000000000010001 | 0000000000000011 | 0 | 0 | 0 | 1 | 1 | 1 | 0000000000000000 | 0 | 1 |
| 0000000000010001 | 0000000000000011 | 0 | 0 | 0 | 0 | 0 | 0 | 0000000000000000 | 0 | 0 |
| 0000000000010001 | 0000000000000011 | 0 | 1 | 0 | 1 | 0 | 1 | 0000000000000000 | 0 | 0 |
)

**Review by kochaika — CHANGES_REQUESTED** [review]
Still failing tests

**Comment by 1MRUN** [comment]
> Still failing tests

I am sorry for such a long reply, not its should be fine.

**Comment by 1MRUN** [comment]
I am sorry, but which code should be fixed ? I thought the problem was only with ALU.

**Pull request merged**
